version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: octoprint-remote_app_1
      APP_PORT: "80"

  app:
    image: alpine
    command: [ "sleep", "infinity" ]
    restart: unless-stopped
